LOAD DATA INFILE 'supplier.dat'
INTO TABLE supplier
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'ingredient.dat'
INTO TABLE ingredient
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'dish.dat'
INTO TABLE dish
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'chef.dat'
INTO TABLE chef
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'appliance.dat'
INTO TABLE appliance
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'used_in.dat'
INTO TABLE used_in
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'cooked_by.dat'
INTO TABLE cooked_by
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'cooked_using.dat'
INTO TABLE cooked_using
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'used_by.dat'
INTO TABLE used_by
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'diet_restrictions.dat'
INTO TABLE diet_restrictions
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'specialties.dat'
INTO TABLE specialties
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';